name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Publish
      - name: publish EasyAbp.CacheManagement.Application.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.CacheManagement.Application/EasyAbp.CacheManagement.Application.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          
      - name: publish EasyAbp.CacheManagement.Application.Contracts.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.CacheManagement.Application.Contracts/EasyAbp.CacheManagement.Application.Contracts.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.CacheManagement.Domain.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.CacheManagement.Domain/EasyAbp.CacheManagement.Domain.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.CacheManagement.Domain.Shared.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.CacheManagement.Domain.Shared/EasyAbp.CacheManagement.Domain.Shared.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.CacheManagement.EntityFrameworkCore.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.CacheManagement.EntityFrameworkCore/EasyAbp.CacheManagement.EntityFrameworkCore.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.CacheManagement.HttpApi.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.CacheManagement.HttpApi/EasyAbp.CacheManagement.HttpApi.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.CacheManagement.HttpApi.Client.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.CacheManagement.HttpApi.Client/EasyAbp.CacheManagement.HttpApi.Client.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.CacheManagement.MongoDB.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.CacheManagement.MongoDB/EasyAbp.CacheManagement.MongoDB.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.CacheManagement.Web.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.CacheManagement.Web/EasyAbp.CacheManagement.Web.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      # Drivers
      - name: publish EasyAbp.CacheManagement.StackExchangeRedis.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: driver/EasyAbp.CacheManagement.StackExchangeRedis/EasyAbp.CacheManagement.StackExchangeRedis.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}